namespace TechC.MagichesBand.Core
{
    public enum SoundType
    {
        TitleBGM,
        SlimeBGM,
        DragonBGM,
        BossBGM,
        Boss2BGM,
        EndingRollBGM,
        EndingBGM,
        StatusUp,
        PlayerFootstep,
        ButtonNavi,
        ButtonSelect,
        ButtonCancel,
        MenuSlide,
        AreaMovement,
        Explosion,
        Shoot,
        Damage,
        ItemGet,
        Potion,
        MPotion,
        Charge,
        Fire,
        Bite,
        Breath,
        Rain,
        Electricity,
        Thunder,
        BlackHole,
        Defeated
    }
}